;;; test_ai-code-discussion.el --- Tests for ai-code-discussion.el -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: Apache-2.0

;;; Commentary:
;; Tests for ai-code-discussion.el.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'dired)
(require 'ai-code-change)
(require 'ai-code-discussion)

(defvar org-roam-directory)

(ert-deftest ai-code-test-explain-dired-uses-marked-files-as-git-relative-context ()
  "Test that marked Dired files are explained using git relative paths."
  (let (captured-initial-prompt captured-final-prompt)
    (cl-letf (((symbol-function 'dired-get-filename)
               (lambda (&rest _) "/tmp/project/a.el"))
              ((symbol-function 'dired-get-marked-files)
               (lambda (&rest _) '("/tmp/project/a.el" "/tmp/project/b.el")))
              ((symbol-function 'ai-code--get-git-relative-paths)
               (lambda (files)
                 (mapcar #'file-name-nondirectory files)))
              ((symbol-function 'ai-code-read-string)
               (lambda (_prompt initial-input &optional _candidate-list)
                 (setq captured-initial-prompt initial-input)
                 initial-input))
              ((symbol-function 'ai-code--insert-prompt)
               (lambda (prompt)
                 (setq captured-final-prompt prompt))))
      (ai-code--explain-dired)
      (should (string-match-p (regexp-quote "Please explain the selected files or directories.") captured-initial-prompt))
      (should (string-match-p (regexp-quote "\nFiles:\n@a.el\n@b.el") captured-initial-prompt))
      (should (equal captured-final-prompt captured-initial-prompt)))))

(ert-deftest ai-code-test-explain-with-scope-selection-routes-to-code-change ()
  "Test that scope selection can dispatch to code-change explanation."
  (let (code-change-called)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (&rest _args) "code change"))
              ((symbol-function 'ai-code--explain-code-change)
               (lambda ()
                 (setq code-change-called t))))
      (ai-code--explain-with-scope-selection)
      (should code-change-called))))

(ert-deftest ai-code-test-explain-code-change-github-pr-builds-prompt ()
  "Test that GitHub PR change explanation builds the expected prompt."
  (let (captured-initial-prompt captured-final-prompt)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (&rest _args) "GitHub PR"))
              ((symbol-function 'ai-code--pull-or-review-source-instruction)
               (lambda (review-source &optional review-mode)
                 (should (eq review-source 'github-mcp))
                 (should (eq review-mode 'explain-code-change))
                 "Use GitHub MCP server to inspect the pull request diff and metadata."))
              ((symbol-function 'ai-code-read-string)
               (lambda (prompt &optional initial-input _candidate-list)
                 (cond
                  ((string-match-p "Pull request URL:" prompt)
                   "https://github.com/acme/demo/pull/123")
                  ((string-match-p "Prompt:" prompt)
                   (setq captured-initial-prompt initial-input)
                   initial-input)
                  (t initial-input))))
              ((symbol-function 'ai-code--format-repo-context-info)
               (lambda ()
                 "\nRepo context: demo"))
              ((symbol-function 'ai-code--insert-prompt)
               (lambda (prompt)
                 (setq captured-final-prompt prompt))))
      (ai-code--explain-code-change 'github-mcp)
      (should (string-match-p "https://github.com/acme/demo/pull/123"
                              captured-initial-prompt))
      (should (string-match-p "Use GitHub MCP server"
                              captured-initial-prompt))
      (should (string-match-p "focus on understanding the change"
                              (downcase captured-initial-prompt)))
      (should (string-match-p "Repo context: demo"
                              captured-initial-prompt))
      (should (equal captured-final-prompt captured-initial-prompt)))))

(ert-deftest ai-code-test-explain-code-change-branch-range-builds-prompt ()
  "Test that base..branch change explanation builds the expected prompt."
  (let (captured-initial-prompt captured-final-prompt)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (&rest _args) "base..branch"))
              ((symbol-function 'ai-code-read-string)
               (lambda (prompt &optional initial-input _candidate-list)
                 (cond
                  ((string-match-p "Base branch:" prompt) "main")
                  ((string-match-p "Branch to explain:" prompt) "feature/demo")
                  ((string-match-p "Prompt:" prompt)
                   (setq captured-initial-prompt initial-input)
                   initial-input)
                  (t initial-input))))
              ((symbol-function 'ai-code--git-root)
               (lambda (&optional _dir)
                 "/tmp/project/"))
              ((symbol-function 'ai-code--format-repo-context-info)
               (lambda ()
                 "\nRepo context: demo"))
              ((symbol-function 'ai-code--insert-prompt)
               (lambda (prompt)
                 (setq captured-final-prompt prompt))))
      (ai-code--explain-code-change)
      (should (string-match-p "main\\.\\.feature/demo" captured-initial-prompt))
      (should (string-match-p "git diff" (downcase captured-initial-prompt)))
      (should (string-match-p "Path: /tmp/project/" captured-initial-prompt))
      (should (string-match-p "Repo context: demo" captured-initial-prompt))
      (should (equal captured-final-prompt captured-initial-prompt)))))

(ert-deftest ai-code-test-explain-code-change-commit-builds-prompt ()
  "Test that single-commit change explanation builds the expected prompt."
  (let (captured-initial-prompt captured-final-prompt)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (&rest _args) "commit"))
              ((symbol-function 'ai-code-read-string)
               (lambda (prompt &optional initial-input _candidate-list)
                 (cond
                  ((string-match-p "Commit hash:" prompt) "abc1234")
                  ((string-match-p "Prompt:" prompt)
                   (setq captured-initial-prompt initial-input)
                   initial-input)
                  (t initial-input))))
              ((symbol-function 'ai-code--git-root)
               (lambda (&optional _dir)
                 "/tmp/project/"))
              ((symbol-function 'ai-code--format-repo-context-info)
               (lambda ()
                 "\nRepo context: demo"))
              ((symbol-function 'ai-code--insert-prompt)
               (lambda (prompt)
                 (setq captured-final-prompt prompt))))
      (ai-code--explain-code-change)
      (should (string-match-p "abc1234" captured-initial-prompt))
       (should (string-match-p "git show" (downcase captured-initial-prompt)))
       (should (string-match-p "Path: /tmp/project/" captured-initial-prompt))
       (should (string-match-p "Repo context: demo" captured-initial-prompt))
       (should (equal captured-final-prompt captured-initial-prompt)))))

(ert-deftest ai-code-test-read-note-request-uses-dedicated-history ()
  "Test that note requests use dedicated persistent minibuffer history."
  (let ((captured-prompt nil)
        (captured-history nil))
    (cl-letf (((symbol-function 'read-string)
               (lambda (prompt &optional initial-input history &rest _args)
                 (setq captured-prompt prompt)
                 (setq captured-history history)
                 initial-input)))
      (should (equal (ai-code--read-note-request)
                     ai-code-discussion--default-note-request))
      (should (equal captured-prompt "Specification for the note? "))
      (should (eq captured-history 'ai-code-note-request-history))
      (should (memq 'ai-code-note-request-history savehist-additional-variables)))))

(ert-deftest ai-code-test-ask-question-routes-to-implement-todo-on-todo-comment ()
  "Test `ai-code-ask-question' calls `ai-code-implement-todo' when on a TODO comment."
  (with-temp-buffer
    (setq buffer-file-name "test.el")
    (setq-local comment-start ";")
    (setq-local comment-end "")
    (insert ";; TODO: implement feature\n")
    (goto-char (point-min))

    (let (implement-todo-called)
      (cl-letf (((symbol-function 'ai-code--get-clipboard-text) (lambda () nil))
                ((symbol-function 'ai-code-implement-todo)
                 (lambda (_arg &optional _default-action) (setq implement-todo-called t)))
                ((symbol-function 'ai-code--ask-question-file)
                 (lambda (_ctx) (error "Should not reach ask-question-file")))
                ((symbol-function 'region-active-p) (lambda () nil)))

        (ai-code-ask-question nil)

        (should implement-todo-called)))))

(ert-deftest ai-code-test-ask-question-falls-through-on-non-todo ()
  "Test `ai-code-ask-question' calls `ai-code--ask-question-file' on non-TODO lines."
  (with-temp-buffer
    (setq buffer-file-name "test.el")
    (setq-local comment-start ";")
    (setq-local comment-end "")
    (insert "some code line\n")
    (goto-char (point-min))

    (let (ask-file-called)
      (cl-letf (((symbol-function 'ai-code--get-clipboard-text) (lambda () nil))
                ((symbol-function 'ai-code-implement-todo)
                 (lambda (_arg) (error "Should not reach implement-todo")))
                ((symbol-function 'ai-code--ask-question-file)
                 (lambda (_ctx) (setq ask-file-called t)))
                ((symbol-function 'region-active-p) (lambda () nil)))

        (ai-code-ask-question nil)

        (should ask-file-called)))))

(ert-deftest ai-code-test-ask-question-routes-to-implement-todo-on-org-headline ()
  "Test `ai-code-ask-question' calls `ai-code-implement-todo' on Org TODO headline."
  (with-temp-buffer
    (require 'org)
    (setq buffer-file-name "plan.org")
    (insert "* TODO Build search feature\n")
    (org-mode)
    (goto-char (point-min))

    (let (implement-todo-called)
      (cl-letf (((symbol-function 'ai-code--get-clipboard-text) (lambda () nil))
                ((symbol-function 'ai-code-implement-todo)
                 (lambda (_arg &optional _default-action) (setq implement-todo-called t)))
                ((symbol-function 'ai-code--ask-question-file)
                 (lambda (_ctx) (error "Should not reach ask-question-file")))
                ((symbol-function 'region-active-p) (lambda () nil)))

        (ai-code-ask-question nil)

        (should implement-todo-called)))))

(ert-deftest ai-code-test-ask-question-passes-ask-question-action ()
  "Test that `ai-code-ask-question' passes \"Ask question\" as default-action."
  (with-temp-buffer
    (setq buffer-file-name "test.el")
    (setq-local comment-start ";")
    (setq-local comment-end "")
    (insert ";; TODO: implement feature\n")
    (goto-char (point-min))

    (let (captured-default-action)
      (cl-letf (((symbol-function 'ai-code--get-clipboard-text) (lambda () nil))
                ((symbol-function 'ai-code-implement-todo)
                 (lambda (_arg &optional default-action)
                   (setq captured-default-action default-action)))
                ((symbol-function 'region-active-p) (lambda () nil)))

        (ai-code-ask-question nil)

        (should (equal captured-default-action "Ask question"))))))

(ert-deftest ai-code-test-ask-question-routes-to-implement-todo-on-plain-org-headline ()
  "Test `ai-code-ask-question' routes to `ai-code-implement-todo' on plain Org headline."
  (with-temp-buffer
    (require 'org)
    (setq buffer-file-name "notes.org")
    (insert "* Regular heading\n")
    (org-mode)
    (goto-char (point-min))

    (let (implement-todo-called)
      (cl-letf (((symbol-function 'ai-code--get-clipboard-text) (lambda () nil))
                ((symbol-function 'ai-code-implement-todo)
                 (lambda (_arg &optional _default-action)
                   (setq implement-todo-called t)))
                ((symbol-function 'ai-code--ask-question-file)
                 (lambda (_ctx) (error "Should not reach ask-question-file")))
                ((symbol-function 'region-active-p) (lambda () nil)))

        (ai-code-ask-question nil)

        (should implement-todo-called)))))

(ert-deftest ai-code-test-take-notes-org-buffer-sends-insert-prompt ()
  "Test `ai-code-take-notes' sends an AI prompt for Org insertion."
  (with-temp-buffer
    (require 'org)
    (org-mode)
    (setq buffer-file-name "/tmp/current-notes.org")
    (insert "* Existing\n")
    (goto-char (point-min))
    (let ((note-request-default nil)
           (captured-prompt nil)
           (captured-history nil)
           (tmp-dir (make-temp-file "ai-code-notes-org" t)))
      (cl-letf (((symbol-function 'read-string)
                 (lambda (_prompt initial-input history &rest _args)
                   (unless note-request-default
                     (setq note-request-default initial-input))
                   (setq captured-history history)
                   initial-input))
                ((symbol-function 'ai-code-read-string)
                 (lambda (_prompt initial-input &optional _candidate-list)
                   initial-input))
                ((symbol-function 'ai-code--insert-prompt)
                 (lambda (prompt)
                   (setq captured-prompt prompt)))
                ((symbol-function 'ai-code--ensure-files-directory)
                 (lambda ()
                   tmp-dir)))
        (unwind-protect
            (progn
              (ai-code-take-notes)
              (should (equal note-request-default "Content of the most recent AI output"))
              (should (eq captured-history 'ai-code-note-request-history))
              (should captured-prompt)
              (should (string-match-p (regexp-quote "Insert the note into the current Org file")
                                      captured-prompt))
              (should (string-match-p (regexp-quote "/tmp/current-notes.org")
                                      captured-prompt))
              (should (string-match-p (regexp-quote "Content of the most recent AI output")
                                      captured-prompt))
              (should (memq 'ai-code-note-request-history savehist-additional-variables)))
          (ignore-errors (delete-directory tmp-dir t)))))))

(ert-deftest ai-code-test-take-notes-non-org-sends-create-prompt-under-org-roam ()
  "Test `ai-code-take-notes' sends an AI prompt for org-roam note creation."
  (let* ((tmp-root (make-temp-file "ai-code-note-roam" t))
         (org-roam-directory (expand-file-name "roam" tmp-root))
         (default-directory tmp-root)
         (captured-prompt nil)
         (captured-default-prompt nil))
    (unwind-protect
        (with-temp-buffer
          (cl-letf (((symbol-function 'read-string)
                     (lambda (prompt initial-input history &rest _args)
                       (should (eq history 'ai-code-note-request-history))
                       (cond
                        ((string-match-p "specification for the note" (downcase prompt))
                         (or initial-input "Content of the most recent AI output"))
                        (t initial-input))))
                    ((symbol-function 'ai-code-read-string)
                     (lambda (prompt initial-input &optional _candidate-list)
                       (cond
                        ((string-match-p "Prompt:" prompt)
                         (setq captured-default-prompt initial-input)
                         initial-input)
                        (t initial-input))))
                    ((symbol-function 'ai-code--ensure-files-directory)
                     (lambda ()
                       (expand-file-name ".ai.code.files" tmp-root)))
                    ((symbol-function 'ai-code--org-roam-ready-p)
                     (lambda () t))
                    ((symbol-function 'ai-code--get-most-recent-ai-session-output)
                     (lambda ()
                       "Captured in roam"))
                    ((symbol-function 'y-or-n-p)
                     (lambda (_prompt) t))
                    ((symbol-function 'require)
                     (lambda (_feature &optional _noerror &rest _args)
                       nil))
                    ((symbol-function 'ai-code--insert-prompt)
                     (lambda (prompt)
                       (setq captured-prompt prompt))))
            (ai-code-take-notes)
            (should captured-prompt)
            (should (string-match-p (regexp-quote "Create a new Org note file")
                                    captured-prompt))
            (should (string-match-p (regexp-quote (file-name-as-directory org-roam-directory))
                                    captured-prompt))
            (should (string-match-p (regexp-quote "run org-roam-db-sync")
                                    captured-prompt))))
      (ignore-errors (delete-directory tmp-root t)))))

(ert-deftest ai-code-test-take-notes-non-org-sends-create-prompt-with-selected-directory ()
  "Test `ai-code-take-notes' uses selected directory in creation prompt."
  (let* ((tmp-root (make-temp-file "ai-code-note-dir" t))
         (default-directory tmp-root)
         (asked-directory-default nil)
         (captured-prompt nil)
         (captured-default-prompt nil))
    (unwind-protect
        (with-temp-buffer
          (cl-letf (((symbol-function 'read-string)
                     (lambda (prompt initial-input history &rest _args)
                       (should (eq history 'ai-code-note-request-history))
                       (cond
                        ((string-match-p "specification for the note" (downcase prompt))
                         (or initial-input "Content of the most recent AI output"))
                        (t initial-input))))
                    ((symbol-function 'ai-code-read-string)
                     (lambda (prompt initial-input &optional _candidate-list)
                       (cond
                        ((string-match-p "Prompt:" prompt)
                         (setq captured-default-prompt initial-input)
                         "Edited create prompt")
                        (t initial-input))))
                    ((symbol-function 'ai-code--ensure-files-directory)
                     (lambda ()
                       (expand-file-name ".ai.code.files" tmp-root)))
                    ((symbol-function 'ai-code--get-most-recent-ai-session-output)
                     (lambda ()
                       "General note content"))
                    ((symbol-function 'read-directory-name)
                     (lambda (_prompt _dir default-dir &optional _mustmatch _initial)
                       (setq asked-directory-default default-dir)
                       default-dir))
                    ((symbol-function 'ai-code--insert-prompt)
                     (lambda (prompt)
                       (setq captured-prompt prompt))))
            (ai-code-take-notes)
            (should asked-directory-default)
            (should captured-prompt)
            (should captured-default-prompt)
            (should (string-match-p (regexp-quote ".ai.code.files/")
                                    (file-name-as-directory asked-directory-default)))
            (should (string-match-p (regexp-quote (file-name-as-directory asked-directory-default))
                                    captured-default-prompt))
            (should (equal captured-prompt "Edited create prompt"))))
      (ignore-errors (delete-directory tmp-root t)))))

(ert-deftest ai-code-test-take-notes-does-not-use-gptel ()
  "Test `ai-code-take-notes' does not call GPTel or session-capture helpers."
  (with-temp-buffer
    (require 'org)
    (org-mode)
    (setq buffer-file-name "/tmp/current-notes.org")
    (let ((tmp-dir (make-temp-file "ai-code-notes-no-gptel" t))
          (gptel-called nil)
          (session-capture-called nil))
      (cl-letf (((symbol-function 'read-string)
                 (lambda (_prompt initial-input history &rest _args)
                   (should (eq history 'ai-code-note-request-history))
                   initial-input))
                ((symbol-function 'ai-code-read-string)
                 (lambda (_prompt initial-input &optional _candidate-list)
                   initial-input))
                ((symbol-function 'ai-code--get-most-recent-ai-session-output)
                 (lambda ()
                    (setq session-capture-called t)
                    "Generated by session"))
                ((symbol-function 'ai-code-call-gptel-sync)
                 (lambda (&rest _args)
                   (setq gptel-called t)
                   (error "Should not call GPTel")))
                ((symbol-function 'ai-code--insert-prompt)
                 (lambda (_prompt)))
                ((symbol-function 'ai-code--ensure-files-directory)
                 (lambda ()
                   tmp-dir)))
        (unwind-protect
            (progn
              (ai-code-take-notes)
              (should (not gptel-called))
              (should (not session-capture-called)))
          (ignore-errors (delete-directory tmp-dir t)))))))

(ert-deftest ai-code-test-take-notes-with-prefix-opens-default-note-file ()
  "Test that `ai-code-take-notes' with prefix argument opens the default note file."
  (let ((ai-code-notes-file-name "test-notes.org")
        (captured-file nil))
    (cl-letf (((symbol-function 'ai-code--ensure-files-directory) (lambda () "/tmp/project/.ai.code.files"))
              ((symbol-function 'find-file-other-window)
               (lambda (file) (setq captured-file file) (get-buffer-create "*test-notes*"))))
      (ai-code-take-notes t)
      (should (equal captured-file "/tmp/project/.ai.code.files/test-notes.org")))))

(provide 'test_ai-code-discussion)

;;; test_ai-code-discussion.el ends here
